CREATE TABLE OYA.EVALUATION
(
  EVALUATION_ID          NUMBER                 NOT NULL,
  RECORDED_DATE_TIME     DATE,
  RECORDED_BY_WORKER_ID  NUMBER,
  NOTES_TEXT             VARCHAR2(4000 BYTE),
  EVALUATION_TOOL_ID     NUMBER                 NOT NULL,
  RACF_ID                VARCHAR2(10 BYTE),
  LAST_CHANGED_DATE      DATE,
  COMPLETED_DATE         DATE,
  REQUEST_OFFICE_ID      NUMBER,
  ALTERNATE_WORKER_NAME  VARCHAR2(60 BYTE),
  RISK_LEVEL             VARCHAR2(20 BYTE),
  COMPLETED_FLAG         CHAR(1 BYTE),
  CONFIDENTIAL_FLAG      CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  YOUTH_ID               NUMBER
);

CREATE TABLE OYA.EVALUATIONTOOL
(
  CREATED_BY_WORKER_ID            NUMBER,
  EVALUATION_TOOL_ID              NUMBER        NOT NULL,
  NAME                            VARCHAR2(100 BYTE),
  PURPOSE                         VARCHAR2(100 BYTE),
  PROGRAM                         VARCHAR2(100 BYTE),
  CREATED_DATE                    DATE,
  RACF_ID                         VARCHAR2(10 BYTE),
  LAST_CHANGED_DATE               DATE,
  STATUS_CODE                     VARCHAR2(4 BYTE),
  TYPE_CODE                       VARCHAR2(4 BYTE),
  EXPIRED_DATE                    DATE,
  ACTIVATED_DATE                  DATE,
  VISIBILITY_ID                   NUMBER,
  PROGRAM_TYPE_CODE               VARCHAR2(4 BYTE),
  JJIS_DOCUMENT_DEFINITION_ID     NUMBER,
  DEFAULT_OPENING_TOOL_TAB_CODE   VARCHAR2(4 BYTE),
  REFERRAL_LINK_FLAG              CHAR(1 BYTE),
  ASSESSMENT_LINK_FLAG            CHAR(1 BYTE),
  RISK_LEVEL_EVALUATION_POINT_ID  NUMBER,
  CONFIDENTIAL_FLAG               CHAR(1 BYTE)  DEFAULT 'N'                   NOT NULL,
  SPECIAL_GROUP_MARKER_CODE       VARCHAR2(4 BYTE),
  ASSESSMENT_DATE_DEFAULT_FLAG    CHAR(1 BYTE)  DEFAULT 'N'                   NOT NULL,
  OFFICE_CODE_ID                  NUMBER,
  CATEGORY_CODE                   VARCHAR2(4 BYTE)
);

CREATE TABLE OYA.EVALUATIONPOINT
(
  SCORABLE_FLAG                 VARCHAR2(1 BYTE),
  CATEGORY                      VARCHAR2(100 BYTE),
  EVALUATION_TOOL_ID            NUMBER,
  NUMERIC_LOW_VALUE             NUMBER,
  MEASUREMENT_TYPE_CODE         VARCHAR2(4 BYTE),
  EVALUATION_POINT_ID           NUMBER          NOT NULL,
  NUMERIC_HIGH_VALUE            NUMBER,
  DESCRIPTION                   VARCHAR2(400 BYTE),
  RACF_ID                       VARCHAR2(10 BYTE),
  LAST_CHANGED_DATE             DATE,
  MULTIPLE_SELECTIONS_FLAG      VARCHAR2(1 BYTE),
  SEQ_NUMBER                    NUMBER,
  JJIS_DATA_LINK_ID             NUMBER,
  VALIDATED_BY_STAT_STUDY_FLAG  VARCHAR2(1 BYTE),
  PARENT_EVALUATION_POINT_ID    NUMBER,
  TYPE_CODE                     VARCHAR2(4 BYTE),
  DISCUSSION_TEXT               VARCHAR2(2000 BYTE),
  JJIS_DATA_LINK_CHOICES_ID     NUMBER,
  SCORE_CALC_FUNCTION_CODE      VARCHAR2(4 BYTE),
  ANSWER_IS_SCORE_FLAG          CHAR(1 BYTE),
  INACTIVE_FLAG                 CHAR(1 BYTE),
  READ_ONLY_FLAG_1              CHAR(1 BYTE),
  READ_ONLY_FLAG                CHAR(1 BYTE)    DEFAULT 'N'                   NOT NULL,
  CASE_PLAN_DOMAIN_CODE         VARCHAR2(4 BYTE),
  DISPLAY_DOMAIN_NUMBER         NUMBER,
  DISPLAY_QUESTION_NUMBER       NUMBER,
  MAXIMUM_SCORE                 NUMBER,
  MANDATORY_QUESTION_FLAG       CHAR(1 BYTE)    DEFAULT 'N'                   NOT NULL,
  OVERRIDE_ANSWER_FLAG          CHAR(1 BYTE),
  SPECIAL_MARKER_CODE           VARCHAR2(4 BYTE)
);

CREATE TABLE OYA.EVALUATIONMEASUREMENTCHOICE
(
  MEASUREMENT_CHOICE_ID    NUMBER               NOT NULL,
  SCORE                    NUMBER,
  MEASUREMENT_DESCRIPTION  VARCHAR2(200 BYTE),
  MEASUREMENT_VALUE        VARCHAR2(10 BYTE),
  EVALUATION_POINT_ID      NUMBER               NOT NULL,
  RACF_ID                  VARCHAR2(10 BYTE),
  LAST_CHANGED_DATE        DATE,
  DEFAULT_FLAG             VARCHAR2(1 BYTE),
  SEQ_NUMBER               NUMBER,
  VALUE_CATEGORY_TYPE      VARCHAR2(4 BYTE),
  INACTIVE_FLAG            CHAR(1 BYTE)         DEFAULT 'N'                   NOT NULL,
  FACTOID_DEFINITION_ID    NUMBER
);

CREATE TABLE OYA.EVALUATIONPOINTMEASURE
(
  SCORE                        NUMBER,
  EVALUATION_POINT_ID          NUMBER           NOT NULL,
  EVALUATION_ID                NUMBER           NOT NULL,
  EVALUATION_POINT_MEASURE_ID  NUMBER           NOT NULL,
  MEASURE_VALUE                VARCHAR2(2000 BYTE),
  RACF_ID                      VARCHAR2(10 BYTE),
  LAST_CHANGED_DATE            DATE,
  DATA_LINK_VALUE              VARCHAR2(500 BYTE),
  VALUE_CATEGORY_TYPE          VARCHAR2(4 BYTE),
  VALUE_DESCRIPTION_CLOB       CLOB,
  NOTES_TEXT_CLOB              CLOB
);

CREATE TABLE OYA.EVALUATIONPOINTANSWER
(
  EVALUATION_POINT_ANSWER_ID   NUMBER           NOT NULL,
  EVALUATION_POINT_MEASURE_ID  NUMBER           NOT NULL,
  EVAL_MEASUREMENT_CHOICE_ID   NUMBER           NOT NULL,
  RACF_ID                      VARCHAR2(10 BYTE),
  LAST_CHANGED_DATE            DATE
);

CREATE TABLE OYA.FACTOIDDEFINITION
(
  FACTOID_DEFINITION_ID     NUMBER              NOT NULL,
  FACTOID_DESCRIPTION_TEXT  VARCHAR2(1000 BYTE),
  CATEGORY_CODE             VARCHAR2(4 BYTE),
  TYPICAL_QUESTION_TEXT     VARCHAR2(1000 BYTE),
  TYPICAL_ANSWER_TEXT       VARCHAR2(1000 BYTE),
  HELP_TEXT                 VARCHAR2(3000 BYTE),
  INACTIVE_FLAG             VARCHAR2(1 BYTE),
  RACF_ID                   VARCHAR2(10 BYTE),
  LAST_CHANGED_DATE         DATE
);